# Generated by Django 2.2 on 2019-06-28 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('foodId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=100)),
                ('foodUrl', models.URLField(max_length=100)),
                ('foodmaterial', models.CharField(max_length=100)),
                ('foodVariety', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('heartData', models.FloatField(max_length=50)),
                ('degreeData', models.FloatField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('alarm', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
